# Generated by Django 5.2.17 on 2026-08-23 00:58
# ruff: noqa: RUF012

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_diagnostico", "Em diagnóstico"),
                            ("aguardando_aprovacao", "Aguardando aprovação"),
                            ("em_conserto", "Em conserto"),
                            ("pronto", "Pronto"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="recebido",
                        max_length=25,
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, null=True)),
                (
                    "estimated_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_orders",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "db_table": "service_orders",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["status"], name="so_status_idx"),
                    models.Index(
                        fields=["customer", "status"], name="so_customer_status_idx"
                    ),
                    models.Index(fields=["-created_at"], name="so_created_at_desc_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estimated_budget__gte", Decimal("0.00")),
                            ("estimated_budget__isnull", True),
                            _connector="OR",
                        ),
                        name="service_order_estimated_budget_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "recebido",
                                    "em_diagnostico",
                                    "aguardando_aprovacao",
                                    "em_conserto",
                                    "pronto",
                                    "entregue",
                                    "cancelado",
                                ],
                            )
                        ),
                        name="service_order_status_valid",
                    ),
                ],
            },
        ),
    ]
